//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingPortalApi.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(CategoryMetadata))]
    public partial class Category
    {
        public Category()
        {
            this.ReportingLinks = new HashSet<ReportingLink>();
        }
    
        public int CategoryId { get; set; }
        public string Category1 { get; set; }

        public virtual ICollection<ReportingLink> ReportingLinks { get; set; }
    }
}
