//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingPortalApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportingLink
    {
        public ReportingLink()
        {
            this.Categories = new HashSet<Category>();
        }
    
        public string Title { get; set; }
        public string Link { get; set; }
        public string Description { get; set; }
        public System.DateTime RowInsertedDT { get; set; }
        public int LinkId { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<Category> Categories { get; set; }
    }
}
